### ISSUE TITLE
Gentle plea for merging deprecation and deprecated packages

### ISSUE THREAD

**Issue by mcepl** [briancurtin/deprecation#51]
This just doesn’t make sense. Two tiny packages which do the same, both of them have to be packaged for all Linux/other distributions, all of them checked for security or whatever-else issues. Could you please guys join the effort?

Thank you.

**Comment by briancurtin** [comment]
It's fine as-is.

**Comment by jccurtis** [comment]
@briancurtin if that is the case, can you explain why one would use your package vs `deprecated`? I really appreciate your open source effort here but one could find it confusing that these packages both exist and yet the readme's contain no mention of each other.

**Comment by briancurtin** [comment]
It scratched an itch I had while working on a project within the OpenStack world that needed this functionality, and an OpenStack util library already had its a deprecation library that didn't jive with what we needed.

These questions are kind of odd and out of nowhere, to be frank. PyPI is littered with duplicate projects because that's just what happens, and these two projects (and a few others) have existed fine for years. If someone likes `deprecated` more they can use it; I'm not going to go learn it so I can write about it in my own documentation.

**Comment by jccurtis** [comment]
Gotcha. The confusion in this case is that these packages are so closely named and can be easily confused since both implement a very similar `deprecated` decorator. That said, you are absolutely right that PyPi contains lots of similar packages (thinking of `vcstool` and `vcstools`). In any case, thanks for package and prompt responses.

**Comment by mcepl** [comment]
I see, OpenStack. That explains everything. Thank you.

**Comment by briancurtin** [comment]
> I see, OpenStack. That explains everything. Thank you.

Keep the snark to yourself.

**Comment by mcepl** [comment]
Says somebody who closes bugs with messages like https://github.com/briancurtin/deprecation/issues/51#issuecomment-669862427. When I was filing this issue, I was thinking that one of these packages had to be from OpenStack, but I reprimanded myself, that I shouldn’t be prejudiced, not all NIH syndrome is located in OpenStack developers. Well …

**Comment by briancurtin** [comment]
Get the fuck out of this project forever.
